
export const myProjects = [
  { title: "Aura Store", category: ["E-Commerce", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./AuraParma.png", link: "https://aurayemen.com" },
  { title: "Ahl Almadina Store", category: ["E-Commerce", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./ahlmp.png", link: "https://ahlmp.com" },
  { title: "Smsm Store", category: ["E-Commerce", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./Smsm.png", link: "https://smsm.otekplatform.com" },
  { title: "Al-lord Group", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./al-lord.png", link: "https://allordgroup.com" },
  { title: "Growth ERP Company", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./growth.png", link: "https://growthyemen.com" },
  { title: "U-Tern", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./Utern.png", link: "https://utern.otekplatform.com" },
  { title: "Yemen House", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./Yemen-House.png", link: "https://yemen-house.com" },
  { title: "ShopToday", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./ShopToday.png", link: "" },
  { title: "Bayanat Minist", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./bayanat.png", link: "https://bayanat.dynamicso.com/" },
  { title: "Doktoori", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./daktoori.png", link: "https://daktoori.com" },
  { title: "Alwan Alkhairr", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./alwan.png", link: "https://alkhairr.qa/ar" },
  { title: "Yemen E-market", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./yemenADs.png", link: "https://yemenemarket.com" },
  { title: "Gadah Jadaan", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./gadahJadaan.png", link: "https://ghadajadaan.com" },
  { title: "Portfolio Website", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./portfolio-ui.png", link: "" },
  { title: "E-commerce", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./Ecommerce-UI.png", link: "" },
  { title: "Topic Clone", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./Topic-Clone.png", link: "" },
  { title: "dashboard", category: ["node"], descreption: "Built this User Interface as front end use Node.js", imgPath: "./", link: "" },
  { title: "Ministry Health", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./MinistryHealth.png", link: "https://moh.gov.ye" },
  { title: "Wirxe Clone", category: ["react"], descreption: "Built this User Interface as front end use ReactJS Next js", imgPath: "./WirxeCloneNext-UI.png", link: "" },
  { title: "Hilink Clone", category: ["react"], descreption: "Built this User Interface as front end use ReactJS Next js", imgPath: "./TravelNext-UI.png", link: "" },
  { title: "Coffee Home", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./Coffee.png", link: "" },
]