
export const myProjects = [
  { title: "Aura Store", category: ["E-Commerce", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./AuraParma.png", linkP:"https://aurayemen.com"},
  { title: "Ahl Almadina Store", category: ["E-Commerce", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./ahlmp.png", linkP:"https://ahlmp.com"},
  { title: "Smsm Store", category: ["E-Commerce", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./Smsm.png", linkP:"https://smsm.otekplatform.com"},
  { title: "Al-lord Group", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./al-lord.png", linkP:"https://allordgroup.com"},
  { title: "Growth ERP Company", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./growth.png", linkP:"https://growthyemen.com"},
  { title: "U-Tern", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./Utern.png", linkP:"https://utern.otekplatform.com"},
  { title: "Yemen House", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./Yemen-House.png", linkP:"https://yemen-house.com"},
  { title: "ShopToday", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./ShopToday.png", linkP:"https://github.com/AhmedAlariqi97/today-shop.git"},
  { title: "Bayanat Minist", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./bayanat.png", linkP:"https://bayanat.dynamicso.com/"},
  { title: "Doktoori", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./daktoori.png", linkP:"https://daktoori.com"},
  { title: "Alwan Alkhairr", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./alwan.png", linkP:"https://alkhairr.qa/ar"},
  { title: "Yemen E-market", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./yemenADs.png", linkP:"https://yemenemarket.com"},
  { title: "Gadah Jadaan", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./gadahJadaan.png", linkP:"https://ghadajadaan.com"},
  { title: "Portfolio Website", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./portfolio-ui.png", linkP:"https://github.com/AhmedAlariqi97/portfoilo-UI.git"},
  { title: "E-commerce", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./Ecommerce-UI.png", linkP:"https://github.com/AhmedAlariqi97/ecommerce-ui.git"},
  { title: "Topic Clone", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./Topic-Clone.png", linkP:"https://github.com/AhmedAlariqi97/topic-clone.git"},
  { title: "dashboard", category: ["node"], descreption: "Built this User Interface as front end use Node.js", imgPath: "./", linkP: ""},
  { title: "Ministry Health", category: ["html", "laravel"], descreption: "Built use Html, Css, JavaScript and Laravel 10 with MySql DB", imgPath: "./MinistryHealth.png", linkP:"https://moh.gov.ye"},
  { title: "Wirxe Clone", category: ["react"], descreption: "Built this User Interface as front end use ReactJS Next js", imgPath: "./WirxeCloneNext-UI.png", linkP:"https://github.com/AhmedAlariqi97/wirex-clone.git"},
  { title: "Hilink Clone", category: ["react"], descreption: "Built this User Interface as front end use ReactJS Next js", imgPath: "./TravelNext-UI.png", linkP:"https://github.com/AhmedAlariqi97/travel-ui2.git"},
  { title: "Coffee Home", category: ["html"], descreption: "Built this User Interface as front end use Html, Css, JavaScript", imgPath: "./Coffee.png", linkP:"https://github.com/AhmedAlariqi97/Coffee-Home.git"},
]