
export const mySkills = [
    {title: "Laravel"},
    {title: "PHP"},
    {title: "C#"},
    {title: "Asp.net"},
    {title: "Node.js"},
    {title: "React.js"},
    {title: "Next.js"},
    {title: "JavaScript"},
    {title: "Html"},
    {title: "Css"},
    {title: "Bootstrap"},
    {title: "Tailwind"},
    {title: "jQuery"},
    {title: "SQL Databases"},
    {title: "No-SQL Databases"},
    {title: "System Analyse"},
    {title: "Problem Solving"},
    {title: "Team Leader"},
    {title: "Agile Project Manager"},
    {title: "Scrum"},
    {title: "Git & Github"},
    {title: "Event planning and oversight"},
    {title: "Administrative coordination"},
    {title: "Logistics"},
    {title: "Scheduling"},
    {title: "Creative innovation"},
  ]